services:
  - type: web
    name: juma-tonny-portfolio
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    autoDeployTrigger: commit
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
